Stubbin for osx_version
bign8/status.bign8.info pull request #1
Opened 2017-03-23 05:27 UTC by de1ux

Ok it's not the greatest thing in the world but them svcz

<img width="228" alt="screen shot 2017-03-22 at 11 26 27 pm" src="https://cloud.githubusercontent.com/assets/3915897/24233313/0979d2ce-0f57-11e7-8196-52b9a4113234.png">

<img width="307" alt="screen shot 2017-03-22 at 11 26 34 pm" src="https://cloud.githubusercontent.com/assets/3915897/24233316/0adf5d78-0f57-11e7-981e-2699ea29c611.png">

2017-03-23 05:36 UTC, bign8 commented on osx/bitbar.1m.sh
> +out=$(python /Users/nathanevans/Documents/main.py)
nit x2: full path
nit: according to the bitbar docs, you should be able to name your `main.py` => `bitbar.1m.py` (or preferably `status.1m.py`) and not need a shell script at all

2017-03-23 05:37 UTC, nathanevans-wf requested changes

2017-03-23 05:37 UTC, nathanevans-wf commented on osx/main.py
> +super_secret_proxy_tmpl = "http://status.bign8.info/proxy?url={}"
TODO - obfuscate, what is this, rookie hour?

2017-03-23 05:37 UTC, nathanevans-wf commented on osx/main.py
> +widget_icon = u"\u03F2".encode('utf-8')
TODO - it would be cool to make this red if all service checks are < 300, else red to mimic what the dart app does already

2017-03-23 05:40 UTC, de1ux commented on osx/main.py
> +				result[envName][svcName] = 'XXXX'
Any other colors should indicate magenta, @nathanevans-wf, not XXXX

2017-03-23 05:40 UTC, de1ux commented on osx/main.py
> +		bitbar_out += ";---;" +\
magic string

2017-03-23 05:40 UTC, de1ux commented on osx/main.py
> +		"{} | font=32 color={};".format(env.capitalize(), saltiest_color)+\
magic string

2017-03-23 05:40 UTC, de1ux commented on osx/main.py
> +		bitbar_out += "--{} | color={};".format(svc, bitbar_status_from_http_code(status))
magic string

2017-03-23 05:40 UTC, de1ux commented on osx/main.py
> +widget_icon = u"\u03F2".encode('utf-8')
magic string

2017-03-23 05:41 UTC, de1ux commented on osx/main.py
> +super_secret_proxy_tmpl = "http://status.bign8.info/proxy?url={}"
@bign8 does the proxy server cache results?

2017-05-30 13:45 UTC, bign8 commented on osx/main.py
> +super_secret_proxy_tmpl = "http://status.bign8.info/proxy?url={}"
It caches results for 1s right now to not exhert a large load on any particular server (it is configurable if you would like to spin up your own server).

https://github.com/bign8/status.bign8.info/blob/master/main.go#L38

2019-07-02 15:21 UTC, closed without merging

2019-07-02 15:26 UTC, bign8 commented
Sorry @de1ux, I meant to merge this a while back. I just have been really busy lately and it got lost in the whirlwind of life.  Let me know if you want to revive this at some point.

Hope things are going well.
-@bign8

2019-07-03 01:16 UTC, de1ux commented
No problem at all, just cleaning up my stale stuff.

Likewise! Talk to you soon